### ISSUE TITLE
🚀 [REQUEST] - Setting Continuous Deploy with Improved environmental variable management

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_server#107]
### Describe

Since the Open-Set-Go project is authorized for member information under GitHub OAuth, it is highly dependent on GitHub. This is not related in the production environment, but there are areas where it is difficult to conduct a test in the development and mounting environment.
Open-Set-Go 프로젝트는 GitHub OAuth로 회원정보에 대해 인가를 받고 있기 때문에, GitHub에 대한 종속이 강하다. 이는 production 환경에서는 상관이 없지만, develop, staging 환경에서는 테스트를 진행하기 힘든 부분이 존재한다.

Therefore, we want to divide and manage environmental variables for Local Server (Develop), Staging Server, and Production Server and connect CI/CD to Staging Server and Production Server at the same time.
그렇기 때문에 Local Server(Develop), Staging Server, Production Server에 대한 환경 변수를 나눠서 관리할 수 있도록 나눔과 동시에 Staging Server와 Production Server에 대해서 CI/CD를 연결하고자 한다.

### Reasons

First, if you complete the login through GitHub OAuth, it will be redirected to one predetermined redirect url. However, this is a major obstacle to performing the Staging test and Local test in the Client. Therefore, we want to establish a CI/CD environment.
우선적으로 GitHub OAuth를 통해 로그인을 완료하면, 미리 정해진 1개의 redirect url으로 redirect되게 된다. 하지만, 이는 Client에서 Staging 테스트 및 Local 테스트를 하는 것에 있어서 큰 방해 요소가 된다. 그렇기 때문에 CI/CD 환경을 구축하고자 한다.

### How to Implement Features

We want to create two more GitHub OAuth apps and separate servers for Local Test, Staging Test, and Production to increase productivity.
GitHub OAuth app을 2개 더 만들고, Server를 Local Test 전용, Staging Test 전용, Production 전용으로 분리하여 생산성을 높이고자 한다.

### TODO
- [ ] Separating .env files
- [x] Connecting CI/CD

### Connection

- [ ] Have no effect on other functions
- [X] Other functions need to be changed

**Comment by ymw0407** [comment]
Overall, in a Cloud Run & netify environment, general processes work well. First, let's summarize the remaining issues here.
전반적으로 Cloud Run & netlify 환경에서 일반적인 프로세스들은 잘 진행된다. 우선 남은 이슈들에 대해서 여기에 정리해본다.

#125 - the problems that make we can't use SupportedEnv feature
AgainIoT/Open-Set-Go_client#78 - Refresh causes login to be undone.

**Comment by ymw0407** [comment]
#125 issue resolved by @bentshrimp & @ymw0407 !!
